import  { useEffect, useState } from "react";
import api from "../../utils/api";
import { useSelector } from "react-redux";

const ReportsInst = () => {
  const { user } = useSelector((state) => state.auth);
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [filters, setFilters] = useState({ year: new Date().getFullYear(), reportType: "" });

  useEffect(() => {
    fetchReports();
  }, []);

  // Fetch reports relevant to the instructor
  const fetchReports = async () => {
    setLoading(true);
    try {
      const { data } = await api.get(`/reports`);
      setReports(data);
    } catch (error) {
      console.error("Error fetching reports:", error);
    }
    setLoading(false);
  };

  // Handle filter changes
  const handleFilterChange = (e) => {
    setFilters({ ...filters, [e.target.name]: e.target.value });
  };

  // Filter reports based on year or report type
  const filteredReports = reports.filter(
    (report) =>
      (!filters.year || report.year === parseInt(filters.year)) &&
      (!filters.reportType || report.reportType === filters.reportType)
  );

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold">Reports</h1>

      {/* Filter Section */}
      <div className="mt-4 bg-white p-4 rounded shadow">
        <h2 className="text-lg font-semibold mb-2">Filter Reports</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <input
            type="number"
            name="year"
            value={filters.year}
            onChange={handleFilterChange}
            className="p-2 border rounded"
            placeholder="Year"
          />
          <select name="reportType" value={filters.reportType} onChange={handleFilterChange} className="p-2 border rounded">
            <option value="">All Report Types</option>
            <option value="Course Assignment">Course Assignment</option>
            <option value="Instructor Workload">Instructor Workload</option>
          </select>
        </div>
      </div>

      {/* Reports List */}
      <div className="mt-6 bg-white p-4 rounded shadow">
        <h2 className="text-lg font-semibold mb-2">Available Reports</h2>
        {loading ? (
          <p>Loading reports...</p>
        ) : filteredReports.length === 0 ? (
          <p>No reports found.</p>
        ) : (
          <table className="w-full border-collapse border border-gray-300">
            <thead>
              <tr className="bg-gray-200">
                <th className="border border-gray-300 p-2">Year</th>
                <th className="border border-gray-300 p-2">Report Type</th>
                <th className="border border-gray-300 p-2">Generated By</th>
                <th className="border border-gray-300 p-2">Created At</th>
                <th className="border border-gray-300 p-2">Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredReports.map((report) => (
                <tr key={report._id} className="text-center">
                  <td className="border border-gray-300 p-2">{report.year}</td>
                  <td className="border border-gray-300 p-2">{report.reportType}</td>
                  <td className="border border-gray-300 p-2">{report.generatedBy}</td>
                  <td className="border border-gray-300 p-2">{new Date(report.createdAt).toLocaleDateString()}</td>
                  <td className="border border-gray-300 p-2">
                    <button onClick={() => alert(JSON.stringify(report.data, null, 2))} className="bg-blue-500 text-white px-2 py-1 rounded">
                      View Report
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
};

export default ReportsInst;
